# Site
name: 'The Badely'
description: 'The Badely Blog'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: ''
email: ''
url: "https://thebadely.github.io"

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag

   
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
pagination:
  enabled: true
  per_page: 5  # Her sayfada 5 yazı olsun
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 1
    after: 1





# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
